s/á/\&aacute;/g
s/é/\&eacute;/g
s/í/\&iacute;/g
s/ó/\&oacute;/g
s/ú/\&uacute;/g
s/Á/\&Aacute;/g
s/É/\&Eacute;/g
s/Í/\&Iacute;/g
s/Ó/\&Oacute;/g
s/Ú/\&Uacute;/g
s/ñ/\&ntilde;/g
s/Ñ/\&Ntilde;/g
s/ü/\&uuml;/g
s/Ü/\&Uuml;/g
s/¿/\&iquest;/g
s/¡/&iexcl;/g
